### ISSUE TITLE
更新 lib-not-dr

### ISSUE THREAD

**Issue by shenjackyuanjie** [Casper233/ZZL#1]
lib-not-dr 更新到 0.1.7 啦
可以去看看
给compiler helper加了一个参数
顺便修了bug

**Comment by Casper233** [comment]
芜~
这个程序估计以后也就是咕咕咕了（其实实际使用发现我写的这玩意使用率几乎为0
甚至有一些情况下这玩意还不如自己动手 本来设计是减少工作量的 但是最后还是变成增加工作量了2333
不过还是非常感谢~
